version: "2"
linters:
  default: standard   # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - gosec           # Security checks for Go code
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - goimports       # Checks import statements are formatted
  exclusions:
    generated: lax
