name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write         # Necessary to write a comment
  pull-requests: none

jobs:
  call_reusable_ci:
    name: Standardized CI
    uses: complytime/org-infra/.github/workflows/reusable_ci.yml@main
