name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  call_reusable_ci:
    name: Standardized CI
    uses: marcusburghardt/github-standards/.github/workflows/reusable_ci.yml@main
